name: Add honor or award / 新增獎項
description: Add an honor, scholarship, fellowship, or award.
title: "[Website: Add honor] "
body:
  - type: input
    id: year
    attributes:
      label: Year / 年份
      placeholder: "2026"
    validations: {required: true}
  - type: input
    id: name-en
    attributes:
      label: Honor name (English) / 獎項英文名稱
    validations: {required: true}
  - type: input
    id: name-zh
    attributes:
      label: Honor name (Chinese) / 獎項中文名稱
    validations: {required: true}
  - type: input
    id: org-en
    attributes:
      label: Organization (English) / 頒發單位英文
  - type: input
    id: org-zh
    attributes:
      label: Organization (Chinese) / 頒發單位中文
  - type: input
    id: url
    attributes:
      label: Honor URL / 獎項連結
